spring:
  application:
    name: cashflow-buddy-rest-api
  datasource:
    password: your_password
    username: root
    url: jdbc:mysql://localhost:3306/cashflow_buddy?useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Logging
logging:
  level:
    root: warn
    web: info
    org.hibernate: off
  main:
    banner-mode: off
  server:
    error:
      include-stacktrace: on_param

# Server
server:
  port: 8080
  servlet:
    context-path: /api
